# Generated by Django 2.2.4 on 2020-05-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='last_name',
            new_name='lname',
        ),
    ]
