# Generated by Django 2.2.4 on 2020-05-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quotedby',
            field=models.CharField(default='Albert', max_length=255),
            preserve_default=False,
        ),
    ]
