# Generated by Django 2.2.4 on 2020-05-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_quote_quotedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quotedby',
        ),
    ]
