# Generated by Django 2.2.4 on 2020-05-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_quote_quotedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favoritor',
            field=models.ManyToManyField(related_name='fav_quotes', to='first_app.Register'),
        ),
    ]
